ThreatWatch/incidents/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Optional, NumberRange
from datetime import datetime
from ThreatWatch.enums import IncidentReliability, IncidentType, IndustryType

class IncidentForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    year = IntegerField('Year', validators=[DataRequired(), NumberRange(min=1900, max=datetime.now().year)])
    description = TextAreaField('Description', validators=[DataRequired()])
    impact = TextAreaField('Impact', validators=[DataRequired()])
    actions_taken = TextAreaField('Taken actions', validators=[DataRequired()])
    reliability = SelectField('Reliability', choices=[(choice.value, choice.value) for choice in IncidentReliability], validators=[DataRequired()])
    industry_type = SelectField('Industry', choices=[(choice.value, choice.value) for choice in IndustryType], validators=[DataRequired()])
    incident_type = SelectField('Type', choices=[(choice.value, choice.value) for choice in IncidentType], validators=[Optional()])
    submit = SubmitField('Add incident')

ThreatWatch/incidents/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort, jsonify
from flask_login import current_user, login_required
from datetime import datetime
from ThreatWatch import db
from ThreatWatch.models import Incident
from ThreatWatch.incidents.forms import IncidentForm
from ThreatWatch.enums import AccountStatus, Role
from ThreatWatch.decorators import account_status_required

# Create a Blueprint named 'incidents'
incidents = Blueprint('incidents', __name__)

# Route for creating a new incident (GET and POST requests are accepted)
@incidents.post('/incident/new')
@incidents.get('/incident/new')
@login_required
@account_status_required(AccountStatus.CONFIRMED)
def new_incident():
    # Create a new IncidentForm instance
    form = IncidentForm()
    force_add = request.form.get('force_add', type=bool, default=False)
    if form.validate_on_submit():
        if not force_add:
            # Check for similar incidents first
            title_words = set(form.title.data.split())
            similar_incidents = Incident.query.filter_by(year=form.year.data, industry_type=form.industry_type.data, incident_type=form.incident_type.data).all()
            for inc in similar_incidents:
                if len(title_words.intersection(set(inc.title.split()))) / len(title_words) >= 0.5:
                    return jsonify(status='similar')
        # Create a new Incident instance and populate its attributes from the form data
        incident = Incident(
            title = form.title.data,
            year = form.year.data,
            industry_type = form.industry_type.data,
            reliability = form.reliability.data,
            description = form.description.data,
            incident_type = form.incident_type.data,
            impact = form.impact.data,
            actions_taken = form.actions_taken.data,
            created_date = datetime.utcnow(),
            last_modified_date = datetime.utcnow(),
            author = current_user
        )
        db.session.add(incident)
        db.session.commit()
        flash('Your incident has been created.', 'success')
        return jsonify(status='added')
    # Render the template for creating a new incident
    return render_template('create_incident.html', title='New Incident', form = form, legend='New Incident')

# Route for viewing a specific incident
@incidents.route('/incident/<int:incident_id>')
def incident(incident_id):
    # Retrieve the incident with the specified ID or return a 404 error if not found
    incident = Incident.query.get_or_404(incident_id)
    # Render the template for displaying the incident details
    return render_template('incident.html', title=incident.title, incident=incident)

# Route for updating an existing incident (GET and POST requests are accepted)
@incidents.post('/incident/<int:incident_id>/update')
@incidents.get('/incident/<int:incident_id>/update')
@login_required
@account_status_required(AccountStatus.CONFIRMED)
def update_incident(incident_id):
    # Retrieve the incident with the specified ID or return a 404 error if not found
    incident = Incident.query.get_or_404(incident_id)
    if incident.author != current_user and (incident.author.account_status == AccountStatus.CONFIRMED and current_user.role == Role.ADMIN):
        abort(403)  # If user does not have permission, return a 403 error
    # Create a new IncidentForm instance
    form = IncidentForm()
    form.submit.label.text = 'Update incident'
    if form.validate_on_submit():
        # Update the attributes of the incident with the form data
        incident.title = form.title.data
        incident.year = form.year.data
        incident.industry_type = form.industry_type.data
        incident.reliability = form.reliability.data
        incident.description = form.description.data
        incident.impact = form.impact.data
        incident.actions_taken = form.actions_taken.data
        incident.last_modified_date = datetime.utcnow()
        db.session.commit()
        flash('Your incident has been updated.', 'success')
        return redirect(url_for('incidents.incident', incident_id=incident.id))
    elif request.method == 'GET':
        # Pre-populate the form with the incident's current data
        form.title.data = incident.title
        form.year.data = incident.year
        form.industry_type.data = incident.industry_type
        form.reliability.data = incident.reliability
        form.description.data = incident.description
        form.industry_type.data = incident.industry_type
        form.impact.data = incident.impact
        form.actions_taken.data = incident.actions_taken
    # Render the template for updating the incident
    return render_template('create_incident.html', title='Update Incident', form = form, legend='Update Incident')

# Route for deleting an incident (GET and POST requests are accepted)
@incidents.post('/incident/<int:incident_id>/delete')
@incidents.get('/incident/<int:incident_id>/delete')
@login_required
@account_status_required(AccountStatus.CONFIRMED)
def delete_incident(incident_id):
    # Retrieve the incident with the specified ID or return a 404 error if not found
    incident = Incident.query.get_or_404(incident_id)
    if current_user.account_status == AccountStatus.DISABLED:
        abort(405)  # If user's account is disabled, return a 405 error
    if incident.author != current_user and current_user.role != Role.ADMIN:
        abort(405)  # If user does not have permission, return a 405 error
    # Delete the incident from the database
    db.session.delete(incident)
    db.session.commit()
    flash('Your incident has been deleted.', 'success')
    return redirect(url_for('main.home'))

ThreatWatch/main/routes.py
from flask import render_template, request, Blueprint
from datetime import datetime
from ThreatWatch.models import Incident

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    incidents = Incident.query.all()
    if incidents:
        last_updated_date = Incident.query.order_by(Incident.last_modified_date.desc()).first().last_modified_date
    else:
        last_updated_date = datetime.today().date()
    return render_template('home.html', incidents=incidents, last_updated_date=last_updated_date)

@main.route('/about')
def about():
    return render_template('about.html', title='About')

ThreatWatch/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import desc
from ThreatWatch import db, bcrypt
from ThreatWatch.models import User, Incident
from ThreatWatch.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from ThreatWatch.users.utils import save_picture, send_reset_email, send_confirmation_email
from ThreatWatch.enums import AccountStatus, Role
from ThreatWatch.decorators import account_status_required, admin_required

# Create a Blueprint named 'users'
users = Blueprint('users', __name__)
PER_PAGE = 10

# Registration route
@users.post('/register')
@users.get('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        send_confirmation_email(user)
        flash('Your account has been created. To activate your account, please check your email for a confirmation link.', 'info')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

# Login route
@users.post('/login')
@users.get('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccesful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)

# Logout route
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

# Account management route
@users.post('/account')
@users.get('/account')
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.profile_picture.data:
            picture_file = save_picture(form.profile_picture.data)
            current_user.profile_picture = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.country = form.country.data
        db.session.commit()
        flash('Your account data has been updated.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.country.data = current_user.country
    image_file = url_for('static', filename='profile_pictures/' + current_user.profile_picture)
    return render_template('account.html', title='Account', image_file=image_file, form = form)

# User incidents route
@users.route('/user/<string:username>')
def user_incidents(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    incidents = Incident.query.filter_by(author=user).order_by(desc(Incident.created_date)).paginate(page=page, per_page=5)
    return render_template('user_incidents.html', incidents=incidents, user=user)


# Password reset request route
@users.get('/reset_password')
@users.post('/reset_password')
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

# Password reset token route
@users.get('/reset_password/<token>')
@users.post('/reset_password/<token>')
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated. You are now able to log in.', 'success')
        return redirect(url_for('login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

# Email confirmation route
@users.get('/confirm_email/<token>')
@users.post('/confirm_email/<token>')
def confirm_email(token):
    user = User.verify_confirmation_token(token)
    if user:
        user.account_status = AccountStatus.CONFIRMED
        db.session.commit()
        flash('Your email address has been confirmed.', 'success')
        return redirect(url_for('users.login'))
    else:
        flash('Invalid or expired confirmation link.', 'danger')
        return redirect(url_for('main.home'))

# User accounts management route (admin only)
@users.get('/user_accounts')
@users.post('/user_accounts')
@login_required
@admin_required
def user_accounts():
    page = request.args.get('page', 1, type=int)
    users = User.query.order_by(User.id).paginate(page=page, per_page=3)
    return render_template('user_accounts.html', users=users)

# Disable user route (admin only)
@users.get('/user/<string:username>/disable')
@users.post('/user/<string:username>/disable')
@login_required
@admin_required
def disable_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.role != Role.ADMIN:
        abort(403)
    user.account_status = AccountStatus.DISABLED
    db.session.commit()
    flash('User has been disabled.', 'success')
    return redirect(url_for('users.user_accounts'))

# Activate user route (admin only)
@users.get('/user/<string:username>/activate')
@users.post('/user/<string:username>/activate')
@login_required
@admin_required
def activate_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.role != Role.ADMIN:
        abort(403)
    user.account_status = AccountStatus.CONFIRMED
    db.session.commit()
    flash('User has been activated.', 'success')
    return redirect(url_for('users.user_accounts'))

ThreatWatch/templates/incident.html
{% extends "layout.html" %}
{% block content %}
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h2 style="margin-bottom: 25px;"><i class="fas fa-file-alt"></i> {{ incident.title }}</h2>
            <table class="table table-striped table-responsive"">
              <tr>
                <th width="20%"><i class="far fa-calendar-alt"></i> Event Year:</th>
                <td width="25%">{{ incident.year }}</td>
                <th width="20%"><i class="fas fa-chart-bar"></i> Reliability:</th>
                <td width="35%">{{ incident.reliability }}</td>
              </tr>
              <tr>
                <th width="20%"><i class="fas fa-exclamation-circle"></i> Incident Type: </th>
                <td width="25%">{{ incident.incident_type }}</td>
                <th width="20%"><i class="fas fa-wrench"></i> Industry Type: </th>
                <td width="35%">{{ incident.industry_type }}</td>
              </tr>
              <tr>
                <th><i class="far fa-file-alt"></i> Description:</th>
                <td colspan="3"><p>{{ incident.description }}</p></td>
              </tr>
              <tr>
                <th><i class="fas fa-fire"></i> Impact:</th>
                <td colspan="3"><p>{{ incident.impact }}</p></td>
              </tr>
              <tr>
                <th><i class="fas fa-indent"></i> Action Description:</th>
                <td colspan="3">{{ incident.actions_taken }}</td>
              </tr>
            </table>
            <div class="text-muted">
              <p>Added by
                <a class="username-link" href="{{ url_for('users.user_incidents', username=incident.author.username) }}">{{ incident.author.username }}</a>
                on {{ incident.created_date.strftime('%Y-%m-%d') }}</p>
            </div>
          </div>
          <div class="card-body">
            <p><strong><i class="far fa-calendar"></i> Last Modified Date:</strong> {{ incident.last_modified_date.strftime('%Y-%m-%d') }}</p>
            <p><strong><i class="far fa-user"></i> Created By:</strong>
              <a class="username-link" href="{{ url_for('users.user_incidents', username=incident.author.username) }}">{{ incident.author.username }}</a>
            </p>
            {% if ( incident.author == current_user and current_user.account_status != AccountStatus.DISABLED) or (incident.author.account_status == AccountStatus.DISABLED and current_user.role == Role.ADMIN) %}
              <div class="text-right">
                <a class="btn btn-primary" href="{{ url_for('incidents.update_incident', incident_id=incident.id) }}">
                  <i class="fas fa-pencil-alt"></i> Update
                </a>
                <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"><i class="fas fa-trash"></i> Delete</button>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Delete Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel"><i class="fas fa-exclamation-triangle"></i> Are you sure you want to delete this incident?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('incidents.delete_incident', incident_id=incident.id) }}" method="POST">
            <button class="btn btn-danger" type="submit"><i class="fas fa-trash"></i> Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ThreatWatch/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.css">

    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title> Threat Watch - {{ title }} </title>
    {% else %}
        <title> Threat Watch </title>
    {% endif %}
</head>
<body class="d-flex flex-column min-vh-100">
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Threat Watch</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav ml-md-auto">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('incidents.new_incident') }}">New Incident</a>
                <a class="nav-item nav-link" href="{{ url_for('users.user_incidents', username=current_user.username) }}">My Incidents</a>
                {% if current_user.role == Role.ADMIN %}
                  <a class="nav-item nav-link" href="{{ url_for('users.user_accounts') }}">Registerd Users</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
        <div>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}
          {% endblock %}
        </div>
    </main>

    <footer id="footer" class="dark-bg mt-auto">
      <div class="container inner">
        <div class="row">
          <div class="col-md-6 col-sm-6 inner">
            <h4>About Threat Watch</h4>
            The Threat Watch is a
                      database of incidents of a cyber security nature that have (or could have) affected process control,
industrial automation or Supervisory Control and Data Acquisition (SCADA) systems.
          </div>
        </div><!-- /.row -->
      </div><!-- .container -->

      <div class="footer-bottom">
        <div class="container">
          <p class="pull-left">© 2023 threatwatch.com LLC. All rights reserved.</p>

        </div><!-- .container -->
      </div><!-- .footer-bottom -->
    </footer>

    <!-- jQuery (required for Bootstrap JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="{{ url_for('static', filename='main.js') }}"></script>
</body>
</html>

ThreatWatch/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section col-md-8">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

ThreatWatch/templates/user_accounts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Registered users</h1>
    <div class="content-section">
        <table class="table">
            <thead>
                <tr>
                    <th class="hide_top_border">Username</th>
                    <th class="hide_top_border">Email</th>
                    <th class="hide_top_border">Country</th>
                    <th class="hide_top_border">Account Status</th>
                    <th class="hide_top_border">Incidents Count</th>
                    <th class="hide_top_border">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{% if user.country %}{{ user.country }}{% else %}Not Provided{% endif %}</td>
                        <td>
                            {% if user.account_status ==  AccountStatus.CONFIRMED %}
                                Confirmed
                            {% elif user.account_status == AccountStatus.DISABLED %}
                                Disabled
                            {% else %}
                                Pending
                            {% endif %}
                        </td>
                        <td>{{ user.incidents|length }}</td>
                        <td>
                            {% if user.role != Role.ADMIN %}
                                {% if user.account_status == AccountStatus.CONFIRMED %}
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#disableUserModal{{ user.id }}">Disable account</button>
                                {% elif user.account_status == AccountStatus.DISABLED %}
                                    <button class="btn btn-success" data-toggle="modal" data-target="#activateUserModal{{ user.id }}">Activate account</button>
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if users.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_accounts', page=page_num)}}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_accounts', page=page_num)}}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

    <!-- Disable User Modals -->
    {% for user in users %}
        {% if user.account_status == AccountStatus.CONFIRMED %}
            <div class="modal fade" id="disableUserModal{{ user.id }}" tabindex="-1" role="dialog" aria-labelledby="disableUserModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="disableUserModalLabel">Disable User</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to disable this user?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <a href="{{ url_for('users.disable_user', username=user.username) }}" class="btn btn-danger">Disable</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    <!-- Activate User Modals -->
    {% for user in users %}
        {% if user.account_status == AccountStatus.DISABLED %}
            <div class="modal fade" id="activateUserModal{{ user.id }}" tabindex="-1" role="dialog" aria-labelledby="activateUserModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="activateUserModalLabel">Activate User</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to activate this user?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <a href="{{ url_for('users.activate_user', username=user.username) }}" class="btn btn-success">Activate</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endblock content %}